### ISSUE TITLE
Setup Sentry error tracking

### ISSUE THREAD

**Issue by pastpatryk** [mavend/octoboard#245]
- [x] Sentry for web client
- [x] Sentry for server
- [x] Releases tracking
- [ ] Sourcemaps
- [x] User feedback form
- [x] Slack notifications
- [x] Integrate with GitHub issues
- [x] Remove Airbrake
